//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBooking.HotelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomType
    {
        public int Id { get; set; }
        public string RoomName { get; set; }
        public string ImagePath { get; set; }
        public string CreatedOn { get; set; }
        public string ModifiedOn { get; set; }
        public string Amenities { get; set; }
    }
}
