//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBooking.HotelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traveller
    {
        public int Id { get; set; }
        public Nullable<int> BookingId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Address { get; set; }
        public string FirstName_2 { get; set; }
        public string MiddleName_2 { get; set; }
        public string LastName_2 { get; set; }
        public string CreatedOn { get; set; }
        public string ModifiedOn { get; set; }
    }
}
